from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def build_pdf_report(
    title,
    module_name,
    risk_probability,
    risk_band,
    inputs_display,
    drivers_lines,
    recommendations,
    missing_count=0,
):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    x = 50
    y = height - 60
    line_h = 14

    def write_line(text, bold=False):
        nonlocal y
        if y < 60:
            c.showPage()
            y = height - 60
        c.setFont("Helvetica-Bold" if bold else "Helvetica", 11)
        c.drawString(x, y, str(text)[:110])
        y -= line_h

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    write_line(title, bold=True)
    write_line(f"Module: {module_name}")
    write_line(f"Generated: {now_str}")
    write_line("")

    write_line("Prediction Summary", bold=True)
    write_line(f"Risk probability: {risk_probability:.2f}")
    write_line(f"Risk category: {risk_band}")
    if missing_count > 0:
        write_line(f"Note: {missing_count} value(s) were estimated due to 'Not sure' inputs.")
    write_line("")

    write_line("Inputs", bold=True)
    for k, v in inputs_display.items():
        write_line(f"{k}: {v}")
    write_line("")

    if drivers_lines:
        write_line("Key Drivers (Explainability)", bold=True)
        for d in drivers_lines:
            write_line(f"- {d}")
        write_line("")

    write_line("Recommendations", bold=True)
    for r in recommendations:
        write_line(f"- {r}")
    write_line("")

    write_line("Disclaimer", bold=True)
    write_line("This report is generated by an educational AI system and is NOT medical advice.")
    write_line("Always consult a qualified healthcare professional for clinical decisions.")

    c.save()
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes